### ISSUE TITLE
Randomize the growth time in a range.

### ISSUE THREAD

**Issue by arpan98** [Terasology/WildAnimals#25]
Currently a baby deer grows into an adult in a fixed time. Having a random growth time within a specified range (in the prefab) would be a better way to do this. This is already implemented over in [SimpleFarming](https://github.com/terasology/simplefarming).

Growth is handled in the [WildAnimalsGrowthSystem](https://github.com/Terasology/WildAnimals/blob/master/src/main/java/org/terasology/wildAnimals/WildAnimalsGrowthSystem.java). The [TimeRange component](https://github.com/Terasology/SimpleFarming/blob/master/src/main/java/org/terasology/simpleFarming/components/TimeRange.java) might also be of use.

**Comment by aaron-harris** [comment]
See comments on PR MovingBlocks/Terasology#3129.  I will redo this and resubmit a new PR.

**Comment by casals** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue blah](https://trello.com/c/zlnAPTso/1-issue-blah)
